# Generated by Django 4.1.1 on 2022-09-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
