# Generated by Django 4.1.1 on 2022-09-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name_plural': 'Latest News'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='sponsors',
            options={'verbose_name_plural': 'Sponsorships'},
        ),
        migrations.AlterModelOptions(
            name='welcomenote',
            options={'verbose_name_plural': 'WelcomeNote'},
        ),
    ]
