# Generated by Django 4.1.1 on 2022-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_welcomenote_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_member', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('family_size', models.IntegerField()),
                ('membership_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
