# Generated by Django 4.1.1 on 2022-09-23 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
