# Generated by Django 4.1.1 on 2022-09-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_members_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomenote',
            name='image2',
            field=models.ImageField(default=None, upload_to='mission'),
        ),
    ]
