# Generated by Django 4.1.1 on 2022-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_welcomenote_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomenote',
            name='image2',
        ),
        migrations.AddField(
            model_name='welcomenote',
            name='right_image',
            field=models.ImageField(default=None, upload_to='mission'),
        ),
    ]
