# Generated by Django 4.1.1 on 2022-09-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_welcomenote_image2_welcomenote_right_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcomenote',
            old_name='image',
            new_name='left_image',
        ),
    ]
