# Generated by Django 4.1.1 on 2022-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='year',
            field=models.IntegerField(default=1982),
            preserve_default=False,
        ),
    ]
