# Generated by Django 4.1.1 on 2022-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='committee_members')),
                ('designation', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Committe Members',
            },
        ),
    ]
