# Generated by Django 4.1.1 on 2022-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_committemembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
