# Generated by Django 4.1.1 on 2022-09-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'verbose_name_plural': 'Sponsorships'},
        ),
    ]
