# Generated by Django 4.1.1 on 2022-09-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_alter_sponsorship_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sponsor_note')),
            ],
            options={
                'verbose_name_plural': 'Sponsor Note',
            },
        ),
    ]
