# Generated by Django 4.1.1 on 2022-09-24 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_sponsornote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsornote',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
