# Generated by Django 4.1.1 on 2022-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf_token', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='orders')),
            ],
        ),
    ]
