# Generated by Django 4.1.1 on 2022-09-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='orders'),
        ),
    ]
