# Generated by Django 4.1.1 on 2022-09-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordermodel_qr_code_ordermodel_qr_code_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='qr_code_img_url',
            field=models.URLField(max_length=1000),
        ),
    ]
