# Generated by Django 4.1.1 on 2022-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermodel_qr_code_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('family_count', models.PositiveIntegerField()),
                ('prasad_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Non Members',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='family_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(default=21312, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='prasad_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
