# Generated by Django 4.1.1 on 2022-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='event_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
